### ISSUE TITLE
Trying to load a saved project crashed the app

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#386] opened 2021-03-02 14:43 UTC
I was logged in already and had saved a project yesterday. I tried loading it and the whole browser window went white. Closing the tab and reopening or refreshing the page does nothing to fix the issue.

Not sure if any of this is useful, as I already refreshed the page before checking console.

![image](https://user-images.githubusercontent.com/59652042/109664908-53f73780-7b76-11eb-8d36-4fa1481f50d0.png)

**Comment by oittinen** [comment] 2021-03-02 14:47
The account is mikko.oittinen@gmail.com and the project is the only one saved there.

I had an account registered to thehaywire@gmail.com but per the other reported bug, I couldn't reset the password and access it :D

**Comment by zilahir** [comment] 2021-03-07 17:24
there was 2 individual bug here. one was the missing keys in the persisted store, that got solved by introducing a migration scripts, that runs _before_ every rehydration, and adds the missing keys, if needed. 

the other was caused by saving a wrongly formatted prompter into the database. this got fixed on the backend. ready to be tested.

**Closed** 2021-03-07 19:04 UTC
Labels: :bug: bug, :hourglass: needs testing, :waning_gibbous_moon: priority HIGH
